### ISSUE TITLE
Polymer elements appear to not work when bundled

### ISSUE THREAD

**Issue by 32graham** [aurelia/html-import-template-loader#11]
My views depend on [Polymer Paper Elements](https://elements.polymer-project.org/browse?package=paper-elements). I got this working by following [this guide](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.2/doc/article/integrating-with-polymer). When I try to bundle my views and the Polymer Paper Elements that they depend on by following [this guide](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.2/doc/article/bundling-your-app-for-deploy/7), the Polymer Paper Elements are not included and thus the bundled app does not work.

I have put together a repo that reproduces the problem. It's a fork of `aurelia/skeleton-navigation` with only the minimal changes needed to reproduce the problem.

Using [this repo that reproduces the problem](https://github.com/32graham/skeleton-navigation) navigate to the `skeleton-es2016` directory and run:

``` bash
npm install
jspm install
bower install
gulp bundle
// Serve the files. I like to use the npm package "http-server"
```

Navigate to `/index.html` and observe that on the welcome view, Polymer Paper Elements _are_ working.
Navigate to `/dest_index.html` and observe that the Polymer Paper Elements _are not_ working.

**Comment by EisenbergEffect** [comment]
@ahmedshuhel Can you take a look into this?

**Comment by ahmedshuhel** [comment]
I will be looking into it tomorrow.

**Comment by 32graham** [comment]
Any progress or suggestions here? I can provide any additional information that is needed.

**Comment by EisenbergEffect** [comment]
My guess is that you need to bundle the Polymer elements using their Vulcanizr tool. Aurelia doesn't trace dependencies or understand HTML imports, so you could need to bundle those separately.

**Comment by 32graham** [comment]
@EisenbergEffect: Yes we can make it work using [Vulcanize](https://github.com/Polymer/vulcanize) but the Aurelia docs indicate that there is a better workflow.

> Bundling HTML Imports
>   At this point, if you are thinking: "Well, this is all good but we have already developed an application that uses Polymer and HTML Imports extensively. We want to bundle them as well." As you may already know, we have created a separate plugin aurelia-html-import-template-loader exclusively for this use case.

http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.2/doc/article/bundling-your-app-for-deploy/7

**Comment by EisenbergEffect** [comment]
I think that wording may be a bit misleading. I could be wrong though. I'll need @ahmedshuhel to chime in and indicate whether the bundler will in fact bundle all Polymer code as well or if that separate bundler should be used for that side of the project.

**Comment by ahmedshuhel** [comment]
I will take a look at it tonight and let you know my findings. As far as I know bundler should work unless something is changed in the html-import-loader.

**Comment by ahmedshuhel** [comment]
At the moment only Aurelia Templates works but not the Polymer Elements when bundling this way. @32graham We can supply pattern like this:`['dist/*.html', 'bower_components/**/*.html']` which places all the Polymer Elements in `view-bundle` file but `html-import-template-loader` ignores them currently. 
Could you check how vulcanize fits here like @EisenbergEffect proposed? If we can come up with a general solution, bundler can then use vulcanize to do the steps necessary.

**Comment by 32graham** [comment]
Thanks @ahmedshuhel, that it what I was observing too.

Yeah, I will look into it in more detail and post my findings here.

What we have done currently is to just vulcanize all the elements we are using and include that file in our version control. Then we just import that in index.html and the Polymer elements are available globally. We were having trouble getting IE 11 working when bundled for some reason though.

I'll dig in more and see what I can find.
