### ISSUE TITLE
Problem installing 

### ISSUE THREAD

**Issue by atticushome** [aurelia/html-import-template-loader#13]
I tried to install aurelia html import template loader. It works for me up until version 1.2.2 but all versions after that show this error:

![problem](https://cloud.githubusercontent.com/assets/8708686/16371921/3cb669aa-3c52-11e6-86cf-24ad666a7d3a.jpg)

I have also tried jspm cc and then install, doesn't change anything.
I can install all other aurelia packages, just have a problem with this one.

Thanks in advance.

**Comment by street2geek** [comment]
This is an issue i am also facing using jspm install.

**Comment by fragsalat** [comment]
+1

**Comment by atticushome** [comment]
Any news on this, as it still not working for me

**Comment by EisenbergEffect** [comment]
If someone would like to submit a PR we would be happy to merge it. It seems like it's just a jspm configuration issue.

**Comment by doktordirk** [comment]
@atticushome which jspm versons are you using. i have 0.16.39 and seemingly no problem

**Comment by EisenbergEffect** [comment]
Definitely try updating to 0.16.39 and see if that fixes it. I thought we had solved this issue, so it may be an older jspm bug.

**Comment by atticushome** [comment]
I was using jspm 0.16.15, updated to 0.16.39 and it worked! Thanks a lot.

**Comment by EisenbergEffect** [comment]
Excellent :)
