### ISSUE TITLE
Loader causes Aurelia to NOT find HTML templates in bundle

### ISSUE THREAD

**Issue by sebastiankr** [aurelia/html-import-template-loader#15]
**I'm submitting a bug report**
- **Library Version:**
  1.0.0

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.x
- **Node Version:**
  6.3.1
  
  
- **NPM Version:**
  3.9.5
  
  
- **JSPM OR Webpack AND Version**
  JSPM 0.16.44 
  
  
- **Browser:**
  Chrome 
- **Language:**
  ESNext

**Current behavior:**
Using this plugin with the skeleton-navigation/skeleton-esnext/ breaks when the project is exported. Aurelia templates are not found in the bundle. Copying all *.html templates into the export/dist folder "fixes" the app. 

**Expected/desired behavior:**

- **What is the expected behavior?**
  The loader looks for HTML first in the bundle and then loads HTML imports to support polymer components. If this is not the expected behavior and HTML files are required on the server, then that should be in the documentation. 
- **What is the motivation / use case for changing the behavior?**
  Fewer HTTP requests

**Comment by ardean** [comment]
+1 same problem here :/

**Comment by EisenbergEffect** [comment]
Have you configured the bundler for html imports? There are special settings for that. You can read about that in the jspm bundler documentation: http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/bundling-jspm/8
