### ISSUE TITLE
Plugin not working with standard aurelia-cli setup

### ISSUE THREAD

**Issue by wc-matteo** [aurelia/html-import-template-loader#16]
**I'm submitting a bug report**
- **Library Version:**
  1.0.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  6.3.0
- **NPM Version:**
  3.10.3
- **Browser:**
  Chrome
- **Language:**
  ESNext

**Current behavior:**
Plugin not working. View not loading. Error in the browser's console:

```
vendor-bundle.js:21513 GET http://localhost:9000/app.html 
Unhandled rejection Error: Load timeout for modules: template-registry- ………
```

This user has the exact same issue: http://stackoverflow.com/questions/39127810/aurelia-polymer-using-cli-tool

Is `SystemJS` a requirement?

**Comment by EisenbergEffect** [comment]
At the moment, if you are going to use this plugin, you need to use system.js because we wrote custom bundle logic there to handle the html imports. We haven't brought that functionality over to the cli yet because it's not something that most people need.

We've got a number of other pressing issues related to the cli so this is going to take a lower priority for us. However, if you are interested in doing the work, then we would be happy to take a PR as soon as it's ready.

**Comment by wc-matteo** [comment]
Thank you @EisenbergEffect, I appreciate the response!

A little off-topic, but... could Aurelia's upcoming UI components replace the need for Polymer? I mean, are they sort of equivalent or am I comparing apples to oranges?

**Comment by EisenbergEffect** [comment]
They could, but they are a ways out.

**Comment by jadrake75** [comment]
@EisenbergEffect Can you outline or provide any hints/primers on what you think this needs to get it working.  Perhaps I can afford one of my guys to look at it if you think it is way off.... (of course that was 24 days ago).  We really need this capability in our effort to standardize around our next corporate framework (and the WEB Components is part of that strategy) and Aurelia runtime using the CLI is the other....

**Comment by EisenbergEffect** [comment]
@ahmedshuhel Can you look into this? Perhaps a great first step to getting you working with us on the new CLI would be to look at what it would take to support HTML imports with the cli like we did with jspm/system.js builder.

**Comment by ahmedshuhel** [comment]
@EisenbergEffect I am looking into it. Thanks.

**Comment by codeaid** [comment]
Any update on this? Looks like it's currently impossible to get Polymer working with Aurelia CLI (assuming documentation at http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/integrating-with-polymer is correct).

**Comment by EisenbergEffect** [comment]
Closing this since both the CLI and Polymer have changed significantly since this issue was opened.
