### ISSUE TITLE
Error in loading plugin html-import-template-loader

### ISSUE THREAD

**Issue by SivaJonnala** [aurelia/html-import-template-loader#3]
aurelia.use.plugin('aurelia-html-import-template-loader');
When I am giving this plugin in my app, It giving error like this: 
"Unhandled promise rejection Error: a.normalizeSync is not a function
Error loading http://localhost:9000/dist/login.html!template-registry-entry";

I am using latest versions of jspm.
Can someone tell me how can I fix this issue

**Comment by EisenbergEffect** [comment]
I believe this was resolved elsewhere.
