### ISSUE TITLE
Problem the bundle file in loading the cross domain 

### ISSUE THREAD

**Issue by rvjaywaks** [aurelia/html-import-template-loader#4]
when the view-bundle are on domain1.com/dist/view-bundle.html
and accessing the app in  domain2.com. it will give an file error HTMLImports.min 404.

it's working on chrome browser. But not on Mozilla or Edge.

**Comment by EisenbergEffect** [comment]
That is under the jurisdiction of the webcomponentsjs group that makes the html imports polyfill. They would be the one to ask about that. There may be a restriction on cross-domain calls in the polyfill. I recommend to check with them.
