### ISSUE TITLE
can it be used to load aurelia plugin HTML files?

### ISSUE THREAD

**Issue by samlin99** [aurelia/html-import-template-loader#6]
I wrote aurelia plugins which have html files. During bundle, I tried to bundle every dist/_.html and my-aurelia-plugins/__/_.html but I always received failed load plugin html files. Is this a bug? or html-import-template-loader just loads dist/*.html ONLY?

Thanks,
# 

Error msg:
GET http://localhost:9000/jspm_packages/emrsn/slin/emrsn-panel@1.0.1/emrsn-panel.html 404 (Not Found)A @ system.js:4(anonymous function) @ system.js:4y @ app-bundle.js:55(anonymous function) @ system.js:4(anonymous function) @ system.js:4(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:4i @ app-bundle.js:55(anonymous function) @ app-bundle.js:55n @ app-bundle.js:55
system.js:4 GET http://localhost:9000/jspm_packages/emrsn/rchen/emrsn-alarm-button@0.1.3/emrsn-alarm-button.html 404 (Not Found)A @ system.js:4(anonymous function) @ system.js:4y @ app-bundle.js:55(anonymous function) @ system.js:4(anonymous function) @ system.js:4(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:4i @ app-bundle.js:55(anonymous function) @ app-bundle.js:55n @ app-bundle.js:55
# 

Bundle code:

```
var config = {
  force: true,
  packagePath: '.',   
  bundles: {
    'dist/app-bundle': {
        includes: [
        '[**/*]',
         "aurelia-framework",
        'aurelia-bootstrapper',
        "aurelia-router",
        'aurelia-templating-resources',
        'aurelia-templating-binding',
        'aurelia-templating-router',
        'aurelia-loader-default',
        'aurelia-history-browser',
        'aurelia-logging-console',
        'aurelia-loader',
        'aurelia-html-import-template-loader',
        'aurelia-flux',
        'aurelia-dialog',
        'aurelia-i18n',
        'iscroll',
        'jquery',
        'moment',
        'text'       
      ].concat(deps),
      options: {
        inject: false,
        minify: true
      }
      },
    "dist/view-bundle": {
      htmlimport: true,
      includes: ['dist/**/*.html','jspm_packages/emrsn/**/*.html'],
      options: {
        inject: {
          indexFile : 'index.html',
          destFile : 'dest_index.html',
        }
      }
  }
  }
};
```

**Comment by EisenbergEffect** [comment]
@ahmedshuhel Can you look into this?

**Comment by ahmedshuhel** [comment]
@samlin99 Could you give me the link to the repository that I can work with?

**Comment by samlin99** [comment]
Unfortunately not.. because it is developing within our company product. However you can use aurelia-dialog plugin to test out. You will encounter same situation. 

Thanks,

**Comment by ahmedshuhel** [comment]
@samlin99  Is there any reason you are using `html-import-template-loader` instead of regular `loader`? Just for curiosity. It should work either way though. I will take a look and let you know.

**Comment by samlin99** [comment]
@ahmedshuhel I was following aurelia bundle instructions http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.6/doc/article/bundling-your-app-for-deploy So I used html-import-template-loader. Let me try to use regular loader.

**Comment by ahmedshuhel** [comment]
While you are trying, could you try this with [v0.2.1](https://github.com/aurelia/bundler). There is a slight change in the configuration but you should be able to find the change in [README.md](https://github.com/aurelia/bundler)

**Comment by EisenbergEffect** [comment]
Looks like we need to add further clarification to the docs. I've seen other people get confused and think they need the html-import-template-loader, not realizing that that is only to support Polymer and shouldn't be used otherwise.

**Comment by ahmedshuhel** [comment]
Yes, the doc needs to be updated. Could we make it mult-page? Break the concept/configuration in smaller chunks. Like, In one page we just explain the bundling in general, next we explain the various configuration and defaults, finally, we give a link of another page for `html-import` based bundling.

**Comment by samlin99** [comment]
@ahmedshuhel I removed all the html-import-template-loader and used bundler v0.2.1 but I still encountered same error message on loading aurelia plugin HTML files.. Do you know any reason?

```
var config = {
  force: true,
  packagePath: '.',   
  bundles: {
    'dist/app-bundle': {
        includes: [
        '[**/*]',
        "aurelia-framework",
        'aurelia-bootstrapper',
        "aurelia-router",
        'aurelia-templating-resources',
        'aurelia-templating-binding',
        'aurelia-templating-router',
        'aurelia-loader-default',
        'aurelia-history-browser',
        'aurelia-logging-console',
        'aurelia-flux',
        'aurelia-dialog',
        'aurelia-i18n',
        'iscroll',
        'jquery',
        'moment',
        'text'       
      ].concat(deps),
      options: {
        inject: true,
        minify: true
      }
      },
    "dist/view-bundle": {
      htmlimport: true,
      includes: ['dist/**/*.html','jspm_packages/emrsn/**/*.html'],
      options: {
        inject: {
          indexFile : 'index.html',
          destFile : 'dest_index.html',
        }
      }
  }
  }
};
```

**Comment by ahmedshuhel** [comment]
If you are using v0.2.1 then your configuration should look like this:

``` javascript
var config = {
  force: true,
  bundles: {
    'dist/app-bundle': {
        includes: [
        '[**/*]',
        '**/*.html!text',
        'jspm_packages/emrsn/**/*.html!text',
        "aurelia-framework",
        'aurelia-bootstrapper',
        "aurelia-router",
        'aurelia-templating-resources',
        'aurelia-templating-binding',
        'aurelia-templating-router',
        'aurelia-loader-default',
        'aurelia-history-browser',
        'aurelia-logging-console',
        'aurelia-flux',
        'aurelia-dialog',
        'aurelia-i18n',
        'iscroll',
        'jquery',
        'moment',
        'text'       
      ].concat(deps),
      options: {
        inject: true,
        minify: true
      }
      },
  }
};
```

Notice, no `packagePath` instead, `baseURL` and `configPath`. In your case the defaults will suffice so I omitted them from the config object. Give this a try and let us know.

**Comment by samlin99** [comment]
@ahmedshuhel  @EisenbergEffect 

```
'jspm_packages/emrsn/**/*.html!text' => this would not work for bundler parsing. 
```

I did also try following and not working too. 

```
'jspm_packages/emrsn/**/*.js'
'jspm_packages/emrsn/**/*.html!text'
```

Here is workaround. In each aurelia plugin, I have to add additional three lines. 

```
var deps = require('./package.json').jspm.dependencies;
var deps_all = [];
// Pickup all our components
deps = Object.keys(deps).filter(function(dep) { return /^emrsn-/.test(dep) });
deps_all = deps_all.concat(deps);
deps_all = deps_all.concat(deps.map(function(dep) { return dep + '/*.js' }));
deps_all = deps_all.concat(deps.map(function(dep) { return dep + '/*.html!text' }));
deps_all = deps_all.concat(deps.map(function(dep) { return dep + '/*.css!text' }));
console.log(deps_all);
```

So in each aurelia plugins (only when plugin has html/css file) it will require like following
  'emrsn-dial',
  'emrsn-dial/_.js',
  'emrsn-dial/_.html!text',
  'emrsn-dial/*.css!text',

Thanks,

**Comment by ahmedshuhel** [comment]
I am not really clear about the `deps` your are using here and why. You should not need these things. @EisenbergEffect  We have an example plugin(skeleton-plugin). We could use it in skeleton-navigation and show how to bundle as well. And, update the doc accordingly.

**Comment by cehoffman** [comment]
@ahmedshuhel what @samlin99 is showing in the last comment isn't relevant to this and just deals with how we collect all of our internal components that are used without having to remember to update the bundle config when installing new components or removing unused ones.

**Comment by EisenbergEffect** [comment]
Is this resolved now?
