### ISSUE TITLE
Error installing with jspm

### ISSUE THREAD

**Issue by ninety7** [aurelia/html-import-template-loader#9]
I'm trying to install this package using jspm and I get the following error:

`err  Installing npm:aurelia-html-import-template-loader@1.0.0-beta.1.1.3, no version match for npm:webcomponentsjs@webcomponents%2Fwebcomponentsjs`

I'm no expert at npm/jspm but I don't see any version requirement for the webcomponents package dependency.

Could you fix this?

**Comment by bobpardoe** [comment]
I am getting the same error trying to use the plugin and Polymer with the latest Aurelia Webpack skeleton. 

I don't think they are related but I thought I would mention it.

Bob

**Comment by pfurini** [comment]
Edit you `packages.json` file and add an "overrides" section, like in the below snippet:

```
"jspm": {
    "directories": {
      "baseURL": "/"
    },
    "dependencies": {
      "aurelia-html-import-template-loader": "npm:aurelia-html-import-template-loader@^1.0.0-beta.1.2.0",
    },
    "overrides": {
      "npm:aurelia-html-import-template-loader@1.0.0-beta.1.2.0": {
        "dependencies": {
          "webcomponents/webcomponentsjs": "npm:webcomponents.js"
        }
      }
    }
  }
```

remember that the version after the @ sign in the overrides section must be the exact version installed by the `jspm install` command, so either remove the ^ in the dependencies (to always install that exact version), or change the version in the overrides if you update the version (for example using `jspm update`)

**Comment by zakjan** [comment]
Can this issue be fixed directly in package.json of this library?

**Comment by EisenbergEffect** [comment]
Is it just a matter of updating this `"webcomponentsjs": "webcomponents/webcomponentsjs"` to this `"webcomponentsjs": "npm:webcomponents.js"`

**Comment by zakjan** [comment]
This issue can be closed, it was fixed in https://github.com/aurelia/html-import-template-loader/commit/a5417df2db56af35ffef40d9c0fc32cb4b891cbc#diff-e22b50e740e102c8de5e858dbcd7753dR21
